// Generates the comparison section of docs/benchmarks.md.
//
// The table was generated and the sentences around it were not, so the sentences drifted:
// they claimed a loss of 1.7x that had become 2.0x and a win of 212x that had become
// 229x. A document where the figures are produced and the prose is typed will always
// come apart, so the prose that carries a number is produced too.
//
// It also refuses to write a report that contains a loss nobody has explained. A row we
// lose is worth keeping; a row we lose without a reason on file is a row nobody looked at.
//
//   node bench/report.mjs           measures, then writes the section
//   node bench/report.mjs --check   reads the file only, and does not measure
//
// The two modes ask different questions on purpose. Writing needs a run. Checking must not
// have one: a benchmark is noisy, rows near parity change side between runs, and a check
// that re-measures fails at random and gets ignored. Checking asks what the artifact can
// answer on its own, which is whether it lists the cases we declare and whether every row
// it calls slower has a reason on file.
import { readFileSync, writeFileSync } from "node:fs";
import { run, ratio } from "./versus.mjs";
import { CASES, DECLARED_LOSSES, EVEN_BAND, DIGITS } from "./peers/cases.mjs";

const DOC = new URL("../docs/benchmarks.md", import.meta.url);
const START = "<!-- generated by bench/report.mjs -->";
const END = "<!-- end generated -->";

const ns = (v) => (v === null ? "n/a" : v < 10000 ? `${v.toFixed(0)} ns` : `${(v / 1000).toFixed(1)} us`);
const times = (r) => (r >= 1 ? `${r.toFixed(1)}x faster` : `${(1 / r).toFixed(1)}x slower`);

// Reading the artifact, with no measurement. See the note at the top.
if (process.argv.includes("--check")) {
  const doc = readFileSync(DOC, "utf8");
  const a = doc.indexOf(START), b = doc.indexOf(END);
  if (a === -1 || b === -1) { console.error("docs/benchmarks.md has no generated block"); process.exit(2); }
  const table = doc.slice(a, b).split("\n")
    .filter((l) => l.startsWith("|") && !l.startsWith("|---"))
    .map((l) => l.split("|").map((x) => x.trim()))
    .slice(1);                                        // drop the header
  const labels = table.map((c) => c[1]);
  const expected = CASES.map((c) => c.label);
  const missing = expected.filter((l) => !labels.includes(l));
  const extra = labels.filter((l) => !expected.includes(l));
  const slower = table.filter((c) => /slower/.test(c[c.length - 2])).map((c) => c[1]);
  const declared = new Set(Object.keys(DECLARED_LOSSES).map((k) => CASES.find((c) => c.key === k)?.label));
  const unexplained = slower.filter((l) => !declared.has(l));

  let bad = 0;
  if (missing.length) { bad++; console.error(`  cases not in the document: ${missing.join(", ")}`); }
  if (extra.length) { bad++; console.error(`  rows not in the case list: ${extra.join(", ")}`); }
  if (unexplained.length) { bad++; console.error(`  slower with no reason on file: ${unexplained.join(", ")}`); }
  if (bad) { console.error("\nRegenerate with `node bench/report.mjs`, or record the reason."); process.exit(1); }
  console.log(`benchmarks.md  ${labels.length} rows, ${slower.length} of them slower, each with a reason`);
  process.exit(0);
}

const { targets, rows, absent } = await run();
if (absent.length) {
  // A table missing a column is not a smaller table, it is a different claim. Writing one
  // from a machine that has not installed the targets would publish that claim silently.
  console.error("A comparison target is not installed, so the report would be partial:");
  for (const a of absent) console.error(`  ${a.path.replace("./peers/", "")}  ${a.why}`);
  console.error("\nRun `npm install` in bench/ and try again.");
  process.exit(1);
}
const [subject, peer] = targets;

const losses = [];
for (const r of rows) {
  const rr = ratio(r.cells[0].ns, r.cells[1].ns);
  if (rr !== null && rr < 1 - EVEN_BAND) losses.push({ ...r, rr });
}
const undeclared = losses.filter((l) => !DECLARED_LOSSES[l.key]);
if (undeclared.length) {
  console.error("A row is slower and has no reason on file:");
  for (const l of undeclared)
    console.error(`  ${l.key.padEnd(10)} ${times(l.rr)} against ${peer.name}`);
  console.error("\nAdd it to DECLARED_LOSSES in bench/peers/cases.mjs, with why.");
  process.exit(1);
}

const head = ["operation", ...targets.map((t) => t.name), `vs ${peer.name}`];
const table = [
  `| ${head.join(" | ")} |`,
  `|${head.map((_, i) => (i ? "---:" : "---")).join("|")}|`,
  ...rows.map((r) => {
    const rr = ratio(r.cells[0].ns, r.cells[1].ns);
    const v = rr === null ? "" : Math.abs(rr - 1) <= EVEN_BAND ? "even" :
      rr < 1 ? `**${times(rr)}**` : times(rr);
    return `| ${r.label} | ${r.cells.map((c) => ns(c.ns)).join(" | ")} | ${v} |`;
  }),
];

const wide = rows.find((r) => r.key === "mulWide");
const wideRatio = ratio(wide.cells[0].ns, wide.cells[1].ns);

const section = [
  START,
  "",
  `Measured on ${process.platform}/${process.arch}, ${process.release?.name ?? "node"} ` +
  `${process.versions.node}, against ` +
  targets.slice(1).map((t) => `${t.name} ${t.version}`).join(" and ") +
  `. Every library is set to ${DIGITS} digits with half-even rounding. Lower is better, ` +
  `and a difference inside ${EVEN_BAND * 100}% is called even because that is what the ` +
  "same machine returns between runs.",
  "",
  ...table,
  "",
  `Reproduce with \`node bench/versus.mjs\`, and regenerate this section with ` +
  "`node bench/report.mjs`. Each library is driven from its own file under `bench/peers/`, " +
  "so if one of them is being called wrongly the mistake is in one file and a pull request " +
  "against it is the fix. Results from other processors are worth more to us than any " +
  "number here, since every figure above comes from one machine.",
  "",
  losses.length
    ? "### Where it loses\n\n" + losses.map((l) =>
        `**${l.label}**, ${times(l.rr)} against ${peer.name}. ${DECLARED_LOSSES[l.key]}`).join("\n\n")
    : "### Where it loses\n\nNo row is slower by more than the even band on this run, " +
      "which is a fact about this machine rather than a claim.",
  "",
  "### What the widest row is not",
  "",
  `Multiplication is not the same operation on both sides. denary's is exact and keeps ` +
  `every digit; ${peer.name} rounds the product to its configured precision. At ${DIGITS} ` +
  "digits the inputs are short enough that both results are exact anyway, so that row is a " +
  `direct comparison. At 400 digits it is not: denary returns an 800-digit exact product ` +
  `where ${peer.name} returns ${DIGITS} rounded digits, and denary is still ` +
  `${wideRatio.toFixed(0)} times faster, because a base-1e7 array multiplies in O(n squared) ` +
  "and a BigInt does not. The ratio is reported with that difference stated rather than " +
  "left for the reader to find.",
  "",
  "`toString` is cached on a denary value, so a fresh value is built on every iteration. " +
  "Timing the cache would be timing a property read.",
  "",
  "None of this is the reason to choose denary. Every row here is tens to hundreds of " +
  "nanoseconds, which is not where an application spends its time. These numbers are here " +
  "so that the contract does not have to be paid for in speed.",
  "",
  END,
].join("\n");

const doc = readFileSync(DOC, "utf8");
const a = doc.indexOf(START), b = doc.indexOf(END);
if (a === -1 || b === -1) { console.error(`${DOC.pathname} has no generated block`); process.exit(2); }
const next = doc.slice(0, a) + section + doc.slice(b + END.length);

writeFileSync(DOC, next);
console.log(`docs/benchmarks.md  ${rows.length} rows, ${losses.length} declared loss` +
  (losses.length === 1 ? "" : "es"));
