// Gate H: decem against a peer, with the oracle deciding.
//
// decimal.js is not an oracle. It is the thing being replaced and it guarantees nothing
// about rounding, including a case its own source documents as wrong. A reference needs a
// stronger guarantee than what it judges, or the comparison is two guesses side by side.
//
// So there are three parties. When decem and the peer disagree, the oracle says which of
// them is wrong:
//
//   both agree                       nothing to do
//   differ, oracle sides with us     the peer is wrong, recorded as evidence
//   differ, oracle sides with them   we are wrong, which is a bug
//   differ, declared design choice   covered by a rule, so it passes
//   differ, oracle cannot decide     left as undecided
//
// An undeclared difference fails. That is what turns the differences ledger from prose
// into something checked.
//
// The peer's answers are committed, the same way the oracle's are, and regenerated by
// test/peers/gen-peer.mjs. That keeps the library being replaced out of the dependencies
// of the library replacing it, lets this run from a clean clone with nothing third-party
// fetched, and makes a new release of the peer show up as a diff rather than as a silent
// change of what the ledger is measured against.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as d from "../../src/index.ts";
import { RULES } from "./rules.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const lines = (p) =>
  readFileSync(join(HERE, "../oracle", p), "utf8").split("\n").filter(Boolean).map(JSON.parse);

const peerFile = readFileSync(join(HERE, "expected/decimal-js.jsonl"), "utf8")
  .split("\n").filter(Boolean).map(JSON.parse);
const PEER = peerFile[0];
const peerAnswers = new Map(peerFile.slice(1).map((r) => [r.id, r]));
const peerCompute = (c) => peerAnswers.get(c.id) ?? { skip: true };

// The operations that are closed over decimals here, and so take no precision argument.
const EXACT = new Set(["add", "sub", "mul"]);

function ourCompute(c) {
  try {
    const args = c.args.map(d.dec);
    const p = { ...c.prec, rounding: c.rounding };
    const v = EXACT.has(c.op) ? d[c.op](args[0], args[1])
      : c.op === "div" ? d.div(args[0], args[1], p)
      : d[c.op](args[0], p);
    return { value: d.toString(v) };
  } catch (e) { return { threw: e.constructor.name }; }
}

// Absurdly large results make the comparison itself expensive, so they are excluded and
// the exclusion is reported rather than hidden.
const TOO_BIG = 100000;
const oversized = (s) => typeof s === "string" && s.length > TOO_BIG;

const cases = [...lines("cases/exact.jsonl"), ...lines("cases/approx.jsonl")];
const oracle = new Map([...lines("expected/exact.jsonl"), ...lines("expected/approx.jsonl")]
  .map((e) => [e.id, e]));

const tally = {};
const undeclared = [];
const evidence = [];
const bump = (k) => (tally[k] = (tally[k] ?? 0) + 1);

for (const c of cases) {
  const want = oracle.get(c.id);
  if (!want || want.noOracle) { bump("no oracle"); continue; }
  const peer = peerCompute(c);
  if (peer.skip) { bump("peer lacks the operation"); continue; }
  const ours = ourCompute(c);
  if (oversized(peer.value) || oversized(ours.value)) { bump("oversized, excluded"); continue; }

  const sameAsPeer = !ours.threw && !peer.threw &&
    (() => { try { return d.cmp(d.dec(ours.value), d.dec(peer.value)) === 0; } catch { return false; } })();
  // Agreeing on the value is not agreeing. `cmp` is by value on purpose, so a result the
  // peer normalised and one that kept the specification's exponent compare equal and were
  // counted as agreement, which is how a difference in half the corpus stayed invisible.
  // The spelling is asked separately and needs a rule of its own.
  if (sameAsPeer && ours.value === peer.value) { bump("agree"); continue; }

  // They disagree, so the oracle decides.
  const oracleAgreesWithUs = !ours.threw && !want.error &&
    (() => { try { return d.cmp(d.dec(ours.value), d.dec(want.result)) === 0; } catch { return false; } })();
  const oracleAgreesWithPeer = !peer.threw && !want.error &&
    (() => { try { return d.cmp(d.dec(peer.value), d.dec(want.result)) === 0; } catch { return false; } })();

  const rule = RULES.find((r) => Boolean(r.spelling) === sameAsPeer && r.match(c, ours, peer, want));
  if (rule) {
    bump(`declared difference: ${rule.id}`);
    if (oracleAgreesWithUs && !oracleAgreesWithPeer && evidence.length < 6)
      evidence.push(`  [${rule.id}] ${c.op}(${c.args.join(", ")})\n` +
        `     decem     ${ours.value ?? "raised " + ours.threw}  (matches the oracle)\n` +
        `     decimal.js ${peer.value ?? "raised " + peer.threw}`);
    continue;
  }
  if (sameAsPeer) { bump("spelling differs, undeclared"); }
  else if (oracleAgreesWithUs) { bump("peer is wrong, undeclared"); }
  else if (oracleAgreesWithPeer) { bump("decem is wrong"); }
  else { bump("neither matches the oracle"); }
  if (undeclared.length < 10)
    undeclared.push(`  ${c.id} ${c.op}(${c.args.join(", ")})` +
      (c.prec ? ` @${JSON.stringify(c.prec)} ${c.rounding}` : "") +
      `\n     decem     ${ours.value ?? "raised " + ours.threw}` +
      `\n     decimal.js ${peer.value ?? "raised " + peer.threw}` +
      `\n     oracle     ${want.error ?? want.result}`);
}

console.log(`Gate H (decem vs ${PEER.peer} ${PEER.version}, oracle deciding)  ${cases.length} cases`);
for (const [k, v] of Object.entries(tally).sort((a, b) => b[1] - a[1]))
  console.log(`  ${k.padEnd(26)} ${v}`);
// The ledger states how many of the corpus land in each of the spelling buckets, and a
// figure typed into a sentence beside a figure that is produced is how a document starts
// lying. The gate that produces them is the one that should check them.
let stale = 0;
{
  const ledger = readFileSync(join(HERE, "../../docs/differences.md"), "utf8");
  for (const r of RULES.filter((x) => x.spelling)) {
    const n = tally[`declared difference: ${r.id}`] ?? 0;
    if (!ledger.includes(`puts ${n} of the corpus`)) {
      console.log(`\n  docs/differences.md does not say ${n} for ${r.id}`);
      stale++;
    }
  }
}

if (evidence.length) {
  console.log("\n-- sample differences where the oracle sides with decem --");
  evidence.forEach((e) => console.log(e));
}
if (undeclared.length) {
  console.log("\n-- undeclared differences --");
  undeclared.forEach((u) => console.log(u));
}
process.exit(undeclared.length || stale ? 1 : 0);
